/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kcaxzgomyzuvsghnzufo";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjYXh6Z29teXp1dnNnaG56dWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MzgyMjEsImV4cCI6MjA4NzExNDIyMX0.dHfn1eC6BVrVEw6hSYnIMCg8IAcYIx6WPNO8bhB1LWo";
